//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCore.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebAppCoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebAppCoreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebAppCore.Resources.WebAppCoreResource", typeof(WebAppCoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droplet Count.
        /// </summary>
        public static string DropletCount {
            get {
                return ResourceManager.GetString("DropletCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droplet Identifier.
        /// </summary>
        public static string DropletIdentifier {
            get {
                return ResourceManager.GetString("DropletIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droplet Id/Count.
        /// </summary>
        public static string DropletInformation {
            get {
                return ResourceManager.GetString("DropletInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateDropletInfo.json.
        /// </summary>
        public static string PlateDropleFile {
            get {
                return ResourceManager.GetString("PlateDropleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 96 Wells.
        /// </summary>
        public static string PlateDropleFileDisplay {
            get {
                return ResourceManager.GetString("PlateDropleFileDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string PlateDropleFileId {
            get {
                return ResourceManager.GetString("PlateDropleFileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string PlateDropletDirectory {
            get {
                return ResourceManager.GetString("PlateDropletDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlateDropletInfo_48Wells.json.
        /// </summary>
        public static string PlateDropletInfoFile48 {
            get {
                return ResourceManager.GetString("PlateDropletInfoFile48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 Wells.
        /// </summary>
        public static string PlateDropletInfoFile48Display {
            get {
                return ResourceManager.GetString("PlateDropletInfoFile48Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string PlateDropletInfoFile48Id {
            get {
                return ResourceManager.GetString("PlateDropletInfoFile48Id", resourceCulture);
            }
        }
    }
}
